import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        bg-gradient-to-b from-black via-gray-900 to-gray-800 
        min-h-screen text-white 
        shadow-2xl`}
      >
        <Navbar />
        <div className="mx-auto px-4">
          <div className="mt-16 p-6 bg-gray-900/50 rounded-2xl shadow-xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}